"""Pre-derive the same-edge static-kernel moment integrals J_pq with sympy
and dump them as inline numpy source.

The B-spline solver (`pysim.bspline.BSplinePySim`) needs closed-form
∫∫ (s-α)^p (s'-A)^q / √((s-s')²+a²) ds' ds for p, q ∈ {0..d} on every
same-edge segment pair. Sympy can integrate this in seconds, but doing so
at every module import is slow (8s+) and adds sympy as a runtime dep.

This script runs sympy ONCE to emit `src/pysim/_bspline_static_moments.py`
with the formulas inlined as numpy expressions. The generated file has no
sympy dependency. Re-run this script when you need to extend `max_d`.

Usage:
    .venv/bin/python scripts/derive_bspline_static_moments.py
"""

import pathlib

import sympy as sp
from sympy.printing.numpy import NumPyPrinter

MAX_D = 2

OUT_PATH = (
    pathlib.Path(__file__).resolve().parents[1]
    / "src"
    / "pysim"
    / "_bspline_static_moments.py"
)


def derive_all(max_d):
    s, sp_dummy, alpha, beta, A, B, a = sp.symbols(
        "s sp_dummy alpha beta A B a", real=True, positive=True
    )
    printer = NumPyPrinter()
    lines = []
    for p in range(max_d + 1):
        for q in range(max_d + 1):
            integrand = (
                (s - alpha) ** p
                * (sp_dummy - A) ** q
                / sp.sqrt((s - sp_dummy) ** 2 + a**2)
            )
            inner = sp.integrate(integrand, (sp_dummy, A, B))
            outer = sp.integrate(inner, (s, alpha, beta))
            code = printer.doprint(outer).replace("numpy.", "np.")
            lines.append((p, q, code))
    return lines


def emit(lines, path, max_d):
    body = [
        '"""Inline closed-form J_pq^static = ∫∫ (s-α)^p (s\'-A)^q / √((s-s\')²+a²)',
        f"on a single straight edge, for p, q ∈ {{0..{max_d}}}.",
        "",
        "Generated by scripts/derive_bspline_static_moments.py (do not edit).",
        '"""',
        "",
        "import numpy as np",
        "",
        "",
        "def J_static_moment(p, q, alpha, beta, A, B, a):",
        '    """One static moment integral (without the 1/(4π) prefactor).',
        "    alpha/beta/A/B/a broadcast as numpy arrays.",
        '    """',
    ]
    for idx, (p, q, code) in enumerate(lines):
        prefix = "if" if idx == 0 else "elif"
        body.append(f"    {prefix} (p, q) == ({p}, {q}):")
        body.append(f"        return {code}")
    body.append("    else:")
    body.append(
        f"        raise ValueError(f'(p, q) = ({{p}}, {{q}}) not in [0, {max_d}]²')"
    )
    body.append("")
    path.write_text("\n".join(body))


def main():
    print(f"Deriving J_pq^static for p, q ∈ {{0..{MAX_D}}} (this takes ~10s)…")
    lines = derive_all(MAX_D)
    emit(lines, OUT_PATH, MAX_D)
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
